# 官方配置文档: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  profiles:
    # 获取开发环境中的配置文件, 环境配置文件必须以 application-xxx.yml 的命名方式
    active: dev
